---
- include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - aiksaurus
    - gimp
    - qgis
    - '{{ vim_X11 }}'
    - vlc
    - xclip

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - nautilus-open-terminal
    - vim-enhanced
  when: ansible_os_family == 'RedHat'

- name: install python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  with_items:
    - jupyter
    - line-profiler
    - memory-profiler
