---
- name: include variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - aiksaurus
    - bleachbit
    - gimp
    - jq
    - qgis
    - '{{ vim_X11 }}'
    - vlc
    - xclip

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - nautilus-open-terminal
  when: ansible_os_family == 'RedHat'

- name: update system packages
  package: name=* state=latest
  become: true
  changed_when: False
  when: ansible_os_family == 'RedHat'

- name: update system packages
  apt: update_cache=yes upgrade=dist
  become: true
  when: ansible_os_family == 'Debian'

- name: install python packages
  pip: name={{ item }} virtualenv={{ virtualenv }}
  become: true
  become_user: '{{ target_user }}'
  with_items:
    - bpython
    - line-profiler
    - memory-profiler
    - wdb.server
