---
- include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - aiksaurus
    - bleachbit
    - gimp
    - qgis
    - '{{ vim_X11 }}'
    - vlc
    - xclip

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - nautilus-open-terminal
  when: ansible_os_family == 'RedHat'

- name: install python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  become: true
  become_user: "{{ target_user }}"
  with_items:
    - line-profiler
    - memory-profiler
