---
- name: install base packages 
  hosts: all
  vars:
    - virtualenv: ~/.virtualenvs/crosscompute

  tasks:
    - name: update selected fedora packages
      dnf: name={{item}} state=latest
      sudo: true
      with_items:
        - vim-minimal
    - name: install fedora packages
      dnf: name={{item}} state=latest
      sudo: true
      with_items:
        - Cython
        - aiksaurus
        - autoconf
        - automake
        - bpython
        - gcc
        - gcc-c++
        - git
        - libtool
        - make
        - nautilus-open-terminal
        - pytest
        - python-ipdb
        - python-ipython-notebook
        - python-pudb
        - python-pytest-cov
        - python-virtualenv
        - swig
        - tar
        - tmux
        - unzip
        - vim-X11
        - vim-enhanced
        - wget
        - zlib-devel
    - name: update fedora packages
      dnf: name=* state=latest
      sudo: true
    - name: install python packages
      pip: name={{item}} state=latest virtualenv={{virtualenv}} virtualenv_site_packages=yes extra_args='-I'
      with_items:
        - flake8
        - ipython
        - jedi
        - jupyter
        - pdbpp
        - pip
        - tornado
        - trepan
    - name: clone scripts
      git:
        repo: git://github.com/invisibleroads/scripts.git
        dest: "{{virtualenv}}/opt/scripts"
        update: yes
        accept_hostkey: yes
    - name: setup scripts
      command: "{{virtualenv}}/opt/scripts/setup {{virtualenv}}"
      args:
        chdir: "{{virtualenv}}/opt/scripts"
      changed_when: False
