---
- name: install numerical packages 
  hosts: all
  vars:
    - virtualenv: ~/.virtualenvs/crosscompute
  tasks:
    - name: install fedora packages
      yum: name={{item}} state=latest
      sudo: true
      with_items:
        - GraphicsMagick 
        - blas-devel
        - bzip2-devel
        - freetype-devel
        - h5py
        - hdf5-devel
        - hdf5-mpich
        - lapack-devel
        - libjpeg-devel
        - libpng-devel
        - lzo-devel
        - numpy
        - python-blosc
        - python-matplotlib
        - python-matplotlib-data
        - python-matplotlib-data-fonts
        - python-numexpr
        - python-pandas
        - python-pillow
        - python-psutil
        - python-tables
        - python-xlrd
        - python-xlwt
        - scipy
        - snappy-devel
    - name: install python packages
      pip: name={{item}} state=latest virtualenv={{virtualenv}} virtualenv_site_packages=yes
      with_items:
        - line_profiler
        - lz4
        - memory_profiler
        - numpy
        - openpyxl
        - pandas
        - python-snappy
        - scipy
