---
- name: configure servers
  hosts: servers
  roles:
    - server-environment

- name: configure workers
  hosts: workers
  roles:
    - worker-environment

- name: configure workstations
  hosts: workstations
  roles:
    - server-environment
    - worker-environment
    - workstation-environment
