---
- name: install spatial packages 
  hosts: all
  vars:
    - virtualenv: ~/.virtualenvs/crosscompute
  tasks:
    - name: install fedora packages
      yum: name={{item}} state=latest
      sudo: true
      with_items:
        - expat-devel
        - gdal
        - gdal-devel
        - gdal-python
        - geos
        - geos-devel
        - geos-python
        - libkdtree++-python
        - proj
        - proj-devel
        - proj-epsg
        - proj-nad
        - proj-static
        - python-Rtree
        - python-basemap
        - python-geojson
        - python-numpydoc
        - python-shapely
        - spatialindex
        - spatialindex-devel
    - name: install python packages
      pip: name={{item}} state=latest virtualenv={{virtualenv}} virtualenv_site_packages=yes extra_args='-I'
      with_items:
        - PySAL
        - fiona
        - geometryIO
        - pykdtree
        - rasterio
        - utm
