---
- name: install web packages 
  hosts: all
  vars:
    - virtualenv: ~/.virtualenvs/crosscompute
  tasks:
    - name: install fedora packages
      yum: name={{item}} state=latest
      sudo: true
      with_items:
        - czmq-devel
        - openssl-devel
        - python-beautifulsoup4
        - python-dogpile-cache
        - python-flask
        - python-msgpack
        - python-pyramid
        - python-pyramid-mako
        - python-pyramid-tm
        - python-requests
        - python-sphinx
        - python-sqlalchemy
        - python-transaction
        - python-velruse
        - python-voluptuous
        - python-zmq
        - python-zope-sqlalchemy
        - redis
        - rubygem-sass
    - name: install python packages
      pip: name={{item}} state=latest virtualenv={{virtualenv}} virtualenv_site_packages=yes extra_args='-I'
      with_items:
        - archiveIO
        - imapIO
        - pyramid
        - pyramid_ipython
        - pyramid_debugtoolbar
        - requests[security]
        - rq
        - socketIO-client
        - whenIO
