---
- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - aiksaurus
    - gimp
    - qgis
    - vlc

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - vim-gtk3
  when: ansible_os_family == 'Debian'

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - nautilus-open-terminal
    - vim-X11
    - vim-enhanced
  when: ansible_os_family == 'RedHat'

- name: install python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  with_items:
    - jupyter
    - line-profiler
    - memory-profiler
    - nose-parameterized
