---
- name: install base system packages
  package: name={{ item }} state=present
  with_items:
    - '{{ cc1plus }}'
    - '{{ openssl_devel }}'
    - '{{ python3_cython }}'

- name: install base python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  become_user: "{{ target_user }}"
  with_items:
    - crosscompute
    - crosscompute-types
    - requests[security]
