---
- name: install computational system packages for theano
  package: name={{ item }} state=present
  with_items:
    - '{{ blas_devel }}'
    - '{{ python_devel }}'

- name: install computational python packages for theano
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  become_user: "{{ target_user }}"
  with_items:
    - pydot-ng

- name: install computational python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  become_user: "{{ target_user }}"
  with_items:
    - networkx
    - scikit-learn
    - statsmodels
    - theano
