---
- name: install graphical system packages for matplotlib
  package: name={{ item }} state=present
  with_items:
    - '{{ GraphicsMagick }}'
    - ffmpeg

- name: install graphical system packages
  package: name={{ item }} state=present
  with_items:
    - python3-matplotlib
    - python3-pillow
