---
- name: install graphical system packages for matplotlib
  package: name={{ item }} state=present
  with_items:
    - '{{ GraphicsMagick }}'
    - ffmpeg

- name: install graphical system packages for pillow
  package: name={{ item }} state=present
  with_items:
    - '{{ freetype_devel }}'
    - '{{ lcms2_devel }}'
    - '{{ libjpeg_devel }}'
    - '{{ libtiff_devel }}'
    - '{{ libwebp_devel }}'
    - '{{ tcl_devel }}'
    - '{{ tk_devel }}'
    - '{{ zlib_devel }}'

- name: install graphical system packages
  package: name={{ item }} state=present
  with_items:
    - python3-matplotlib

- name: install graphical python packages
  pip: name={{ item }} virtualenv={{ virtualenv }}
  become_user: "{{ target_user }}"
  with_items:
    - pillow
