---
- name: include variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- include: base.yml
  become: true

- include: numerical.yml
  become: true

- include: graphical.yml
  become: true

- include: computational.yml
  become: true

- include: spatial.yml
  become: true
