---
- name: include variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- import_tasks: base.yml
  become: true

- import_tasks: numerical.yml
  become: true

- import_tasks: graphical.yml
  become: true

- import_tasks: computational.yml
  become: true

- import_tasks: spatial.yml
  become: true
