---
- name: install numerical system packages for pandas
  package: name={{ item }} state=present
  become: true
  with_items:
    - '{{ blosc_devel }}'
    - '{{ python2_lxml }}'
    - '{{ xz_devel }}'

- name: install numerical python packages for pandas
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  become: true
  become_user: "{{ target_user }}"
  with_items:
    - backports.lzma
    - beautifulsoup4
    - blosc
    - boto
    - google-api-python-client
    - html5lib
    - httplib2
    - jinja2
    - oauth2client
    - openpyxl
    - python-gflags
    - xarray
    - xlrd
    - xlwt

- name: install numerical system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - '{{ python2_h5py }}'
    - '{{ python2_numpy }}'
    - '{{ python2_pandas }}'
    - '{{ python2_scipy }}'
