---
- name: install spatial system packages
  package: name={{ item }} state=present
  with_items:
    - '{{ gdal_devel }}'
    - '{{ gdal_python3 }}'
    - '{{ geos_devel }}'
    - '{{ proj_data }}'
    - '{{ proj_devel }}'
    - '{{ spatialindex_devel }}'

- name: install spatial python packages
  pip: name={{ item }} virtualenv={{ virtualenv }}
  become_user: '{{ target_user }}'
  with_items:
    - geojson
    - geometryIO
    - geopy
    - pysal
    - rtree
    - shapely
    - utm
