---
- name: install spatial system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - '{{ gdal_devel }}'
    - '{{ gdal_python }}'
    - '{{ geos_devel }}'
    - '{{ proj_data }}'
    - '{{ proj_devel }}'
    - '{{ python_basemap }}'
    - '{{ python_basemap_data }}'
    - '{{ spatialindex_devel }}'

- name: install spatial python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  become: true
  become_user: "{{ target_user }}"
  with_items:
    - fiona
    - geojson
    - geometryIO
    - geopy
    - pykdtree
    - pysal
    - rasterio
    - rtree
    - shapely
    - utm
