---
- name: include variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- name: set user
  set_fact: target_user={{ lookup('env', 'USER') }}
  when: target_user is undefined and inventory_hostname == 'localhost'

- name: set user
  set_fact: target_user={{ ansible_user }}
  when: target_user is undefined and inventory_hostname != 'localhost'

- name: set virtualenv folder
  set_fact: virtualenv_folder={{ lookup('env', 'HOME') }}/.virtualenvs/{{ virtualenv_name }}
  become: true
  become_user: '{{ target_user }}'

- name: show virtualenv folder
  debug: var=virtualenv_folder

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - '{{ libselinux_python }}'
    - '{{ python2_virtualenv }}'
    - '{{ python3_devel }}'
    - curl
    - gcc
    - git
    - python3-pandas
    - tmux
    - unzip
    - wget

- include: vim.yml
  become: true
  when: ansible_os_family == 'RedHat'

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - redhat-rpm-config
  when: ansible_os_family == 'RedHat'

- include: scripts.yml
  become: true

- include: swap.yml
  become: true
  when: ansible_memtotal_mb < 1024 and ansible_swaptotal_mb < 1

- name: make virtualenv
  pip:
    name: pip
    state: latest
    virtualenv: '{{ virtualenv_folder }}'
    virtualenv_python: python3
    virtualenv_site_packages: yes
  become: true
  become_user: '{{ target_user }}'

- name: install python packages
  pip: name={{ item }} virtualenv={{ virtualenv_folder }}
  become: true
  become_user: '{{ target_user }}'
  with_items:
    - flake8
    - ipdb
    - ipython
    - jedi
    - pdbpp
    - pudb
    - pytest
    - pytest-cov
    - pytest-mock

- name: install system repositories
  package: name={{ item }} state=present
  become: true
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  changed_when: False
  when: ansible_distribution == 'Fedora'
