---
- name: clone scripts
  git:
    accept_hostkey: yes
    depth: 1
    dest: /tmp/invisibleroads-scripts
    repo: git://github.com/invisibleroads/scripts.git
  become_user: '{{ target_user }}'

- name: setup scripts
  command: /tmp/invisibleroads-scripts/setup {{ virtualenv }}
  become_user: '{{ target_user }}'
  changed_when: False

- name: setup scripts for superuser
  command: /tmp/invisibleroads-scripts/setup {{ virtualenv }}
  changed_when: False
