---
- name: clone scripts
  git:
    accept_hostkey: yes
    depth: 1
    dest: '{{ virtualenv }}/opt/scripts'
    repo: git://github.com/invisibleroads/scripts.git
  become: true
  become_user: '{{ target_user }}'

- name: setup scripts
  command: '{{ virtualenv }}/opt/scripts/setup {{ virtualenv }}'
  become: true
  become_user: '{{ target_user }}'
  changed_when: False

- name: clone scripts for superuser
  git:
    accept_hostkey: yes
    depth: 1
    dest: '{{ virtualenv }}/opt/scripts'
    repo: git://github.com/invisibleroads/scripts.git
  become: true

- name: setup scripts for superuser
  command: '{{ virtualenv }}/opt/scripts/setup {{ virtualenv }}'
  become: true
  changed_when: False
