---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "RedHat.yml"

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - "{{ libselinux_python }}"
    - "{{ python2_virtualenv }}"
    - "{{ python_devel }}"
    - gcc
    - git
    - tmux
    - unzip
    - wget

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - redhat-rpm-config
  when: ansible_os_family == 'RedHat'

- name: disable system packages
  package: name={{ item }} state=absent
  become: true
  with_items:
    - cockpit

- include: scripts.yml

- include: swap.yml
  become: true
  when: ansible_memtotal_mb < 1024 and ansible_swaptotal_mb < 1

- name: update system packages
  package: name=* state=latest
  become: true
  changed_when: False
  when: ansible_os_family == 'RedHat'

- name: update system packages
  apt:
    update_cache: yes
    upgrade: dist
  become: true
  when: ansible_os_family == 'Debian'

- name: install system repositories
  package: name={{ item }} state=present
  become: true
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  changed_when: False
  when: ansible_distribution == 'Fedora'

- name: update python packages
  pip: name={{ item }} state=latest virtualenv={{ virtualenv }}
  with_items:
    - pip

- name: install python packages
  pip: name={{ item }} state=present virtualenv={{ virtualenv }}
  with_items:
    - bpython
    - flake8
    - ipdb
    - ipython
    - jedi
    - pdbpp
    - pudb
    - pytest
    - pytest-cov
    - pytest-mock
    - trepan
    - wdb.server
